import AboutUs from '@/components/layout/AboutUs'
import Contacts from '@/components/layout/Contacts'
import Header from '@/components/layout/Header'
import { CartContextProvider } from '@/context/CartContext'
import { NextAuthProvider } from '@/context/Provider'
import { NextUIProvider } from '@nextui-org/react'
import { Roboto } from 'next/font/google'
import { Toaster } from 'react-hot-toast'
import './globals.css'
const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700'] })

export const metadata = {
	title: 'Food-ordering',
	description: 'Generated by create next app',
	icons: {
		icon: '/pizza-logo.png',
	},
}

export default function RootLayout({ children }) {
	return (
		<html lang='en' className='scroll-smooth '>
			<body className={roboto.className}>
				<NextUIProvider >
					<NextAuthProvider>
						<CartContextProvider>
							<Toaster />
							<div className='flex flex-col max-w-4xl mx-auto p-4 min-h-[100vh]'>
								<Header />
								<main className='flex-1'>
									{children}
									<AboutUs />
									<Contacts />
								</main>
								<footer className='border-t p-8 text-center text-gray-500 mt-4 sm:mt-16'>
									&copy; 2024 All rights reserved
								</footer>
							</div>
						</CartContextProvider>
					</NextAuthProvider>
				</NextUIProvider>
			</body>
		</html>
	)
}
